name: personal_cards_manager
description: "Personal Cards Manager. Including MasterCard/Visa/Member Cards/Identify Proof and more."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1
  
  # Local Database
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.2

  # Security & Storage
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.6
  shared_preferences: ^2.2.2
  
  # Generation & UI
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4

  # Utils
  uuid: ^4.3.3
  intl: ^0.19.0
  encrypt: ^5.0.3
  
  # File & Share
  file_picker: ^8.0.0+1
  share_plus: ^9.0.0
  
  # Notifications
  flutter_local_notifications: ^17.1.2
  
  # Navigation
  go_router: ^14.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
